package com.fic.event_management_system.enums;

public enum NotificationType {

    PORTAL_CREATED,
    TRIAL_ACTIVATED,

    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_UPGRADED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_EXPIRING,
    SUBSCRIPTION_EXPIRED,

    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,

    USER_INVITED,
    INVITATION_ACCEPTED,
    INVITATION_REJECTED,

    EVENT_ASSIGNED,
    EVENT_PUBLISHED,
    EVENT_UPDATED,
    EVENT_CANCELLED,
    EVENT_REMINDER,

    REGISTRATION_SUCCESS,
    REGISTRATION_WAITLISTED,
    WAITLIST_CONFIRMED,

    TICKET_GENERATED,
    CERTIFICATE_GENERATED,

    CAPACITY_WARNING,
    DAILY_SUMMARY,

    EMAIL_DELIVERY_FAILED,
    SYSTEM_ALERT
}
