import { useEffect, useState } from "react";
import RoleLayout from "../../layouts/RoleLayout";
import api from "../../api/axiosConfig";
import { filterToActiveEvent, loadRoleAssignments } from "../../utils/roleAssignments";
import "../../styles/Admin.css";

const initial = { title:"", description:"", taskType:"TASK", category:"EVENT_OPERATIONS", priority:"MEDIUM", status:"NOT_STARTED", assignedUserId:"", assignedUserName:"", dueDateTime:"" };
export default function CoordinatorTasks() {
  const [events,setEvents]=useState([]), [eventId,setEventId]=useState(""), [tasks,setTasks]=useState([]), [assignees,setAssignees]=useState([]);
  const [form,setForm]=useState(initial), [message,setMessage]=useState("");
  useEffect(()=>{(async()=>{ try { const id=localStorage.getItem("userId"); const a=await loadRoleAssignments("COORDINATOR",`/coordinator-assignments/coordinator/${id}`); const e=filterToActiveEvent(a).filter(x=>x.active!==false&&x.event?.id).map(x=>x.event); setEvents(e); if(e[0]) setEventId(String(e[0].id)); } catch { setMessage("Unable to load assigned events."); } })();},[]);
  useEffect(()=>{ if(eventId) loadWorkspace(eventId); },[eventId]);
  async function loadWorkspace(id){ const [t,s,v]=await Promise.allSettled([api.get(`/events/${id}/operations/tasks`),api.get(`/staff-assignments/event/${id}`),api.get(`/volunteer-assignments/event/${id}`)]); setTasks(t.status==="fulfilled"?t.value.data||[]:[]); const people=[]; if(s.status==="fulfilled") (s.value.data||[]).forEach(x=>people.push({user:x.staff,role:"Staff"})); if(v.status==="fulfilled") (v.value.data||[]).forEach(x=>people.push({user:x.volunteer,role:"Volunteer"})); setAssignees(people.filter(x=>x.user?.id)); }
  function change(e){ const {name,value}=e.target; if(name==="assignedUserId"){const p=assignees.find(x=>String(x.user.id)===value); setForm({...form,assignedUserId:value,assignedUserName:p?`${p.user.firstName||""} ${p.user.lastName||""}`.trim():""});} else setForm({...form,[name]:value}); }
  async function save(e){e.preventDefault(); try {await api.post(`/events/${eventId}/operations/tasks`,{...form,assignedUserId:Number(form.assignedUserId)}); setForm(initial); setMessage("Task assigned successfully."); loadWorkspace(eventId);} catch(err){setMessage(err.response?.data?.message||"Unable to assign task.");}}
  return <RoleLayout><PageHead title="Tasks" text="Assign operational work to staff and volunteers, then monitor deadlines."/>{message&&<div className="alert alert-info">{message}</div>}
    <div className="admin-bento-card mb-4"><label className="form-label fw-semibold">Assigned event</label><select className="form-select" value={eventId} onChange={e=>setEventId(e.target.value)}>{events.map(e=><option key={e.id} value={e.id}>{e.eventName}</option>)}</select></div>
    <form className="admin-bento-card mb-4" onSubmit={save}><h2 className="h5 fw-bold mb-3">Assign task</h2><div className="row g-3"><Field label="Title" name="title" value={form.title} change={change}/><Select label="Assigned person" name="assignedUserId" value={form.assignedUserId} change={change} options={assignees.map(x=>[x.user.id,`${x.user.firstName} ${x.user.lastName} — ${x.role}`])}/><Select label="Category" name="category" value={form.category} change={change} options={["EVENT_OPERATIONS","REGISTRATION","VENUE_SETUP","GUEST_SUPPORT","SAFETY","LOGISTICS"].map(x=>[x,x.replaceAll("_"," ")])}/><Select label="Priority" name="priority" value={form.priority} change={change} options={["LOW","MEDIUM","HIGH","URGENT"].map(x=>[x,x])}/><Field label="Deadline" name="dueDateTime" type="datetime-local" value={form.dueDateTime} change={change}/><div className="col-12"><label className="form-label fw-semibold">Description</label><textarea className="form-control" name="description" value={form.description} onChange={change}/></div></div><button className="btn btn-primary mt-3" disabled={!eventId||!form.title||!form.assignedUserId}>Assign Task</button></form>
    <div className="admin-bento-card"><h2 className="h5 fw-bold">Task progress</h2><div className="table-responsive"><table className="table align-middle"><thead><tr><th>Task</th><th>Assigned to</th><th>Priority</th><th>Status</th><th>Deadline</th></tr></thead><tbody>{tasks.map(t=><tr key={t.id}><td><b>{t.title}</b><div className="text-muted small">{t.category?.replaceAll("_"," ")}</div></td><td>{t.assignedUserName||"Unassigned"}</td><td>{t.priority}</td><td><span className="badge bg-primary">{String(t.status).replaceAll("_"," ")}</span></td><td>{t.dueDateTime?new Date(t.dueDateTime).toLocaleString():"—"}</td></tr>)}{!tasks.length&&<tr><td colSpan="5" className="text-center text-muted py-4">No tasks assigned yet.</td></tr>}</tbody></table></div></div>
  </RoleLayout>;
}
function PageHead({title,text}){return <div className="mb-4"><h1 className="fw-bold fs-3">{title}</h1><p className="text-muted">{text}</p></div>};
function Field({label,name,value,change,type="text"}){return <div className="col-md-6"><label className="form-label fw-semibold">{label}</label><input required={name==="title"} className="form-control" name={name} type={type} value={value} onChange={change}/></div>};
function Select({label,name,value,change,options}){return <div className="col-md-6"><label className="form-label fw-semibold">{label}</label><select required={name==="assignedUserId"} className="form-select" name={name} value={value} onChange={change}><option value="">Select {label.toLowerCase()}</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>};
