import { useEffect,useState } from "react";
import { Link } from "react-router-dom";
import RoleLayout from "../../layouts/RoleLayout";
import api from "../../api/axiosConfig";
import { filterToActiveEvent, loadRoleAssignments } from "../../utils/roleAssignments";
import "../../styles/Admin.css";
export default function CoordinatorEventDay(){const [events,setEvents]=useState([]),[eventId,setEventId]=useState(""),[data,setData]=useState({sessions:[],resources:[],vendors:[]});
 useEffect(()=>{(async()=>{const id=localStorage.getItem("userId"),a=await loadRoleAssignments("COORDINATOR",`/coordinator-assignments/coordinator/${id}`);const e=filterToActiveEvent(a).filter(x=>x.active!==false&&x.event?.id).map(x=>x.event);setEvents(e);if(e[0])setEventId(String(e[0].id));})();},[]);
 useEffect(()=>{if(!eventId)return;(async()=>{const [s,r,v]=await Promise.allSettled([api.get(`/events/${eventId}/sessions`),api.get(`/events/${eventId}/operations/resources`),api.get(`/events/${eventId}/operations/vendors`)]);setData({sessions:s.status==="fulfilled"?s.value.data||[]:[],resources:r.status==="fulfilled"?r.value.data||[]:[],vendors:v.status==="fulfilled"?v.value.data||[]:[]});})();},[eventId]);
 const event=events.find(x=>String(x.id)===eventId);
 return <RoleLayout><div className="mb-4"><h1 className="fw-bold fs-3">Event Day</h1><p className="text-muted">Coordinate the live schedule, venue, resources, vendors, attendance, and team response.</p></div><div className="admin-bento-card mb-4"><select className="form-select" value={eventId} onChange={e=>setEventId(e.target.value)}>{events.map(e=><option key={e.id} value={e.id}>{e.eventName}</option>)}</select>{event&&<div className="row g-3 mt-1"><Info label="Venue" value={event.venue||event.meetingLink||"Not added"}/><Info label="Starts" value={format(event.startDateTime)}/><Info label="Ends" value={format(event.endDateTime)}/></div>}</div>
 <div className="row g-4 mb-4"><Panel title="Schedule" rows={data.sessions} render={x=>`${x.sessionTitle||x.title||"Session"} — ${x.startTime||x.sessionTime||"Time pending"}`}/><Panel title="Resources" rows={data.resources} render={x=>`${x.name||x.resourceName||"Resource"} — ${x.status||x.quantity||"Available"}`}/><Panel title="Vendors" rows={data.vendors} render={x=>`${x.name||x.vendorName||"Vendor"} — ${x.status||x.serviceCategory||"Confirmed"}`}/></div>
 <div className="admin-bento-card"><h2 className="h5 fw-bold">Live coordination</h2><div className="d-flex flex-wrap gap-2"><Link className="btn btn-primary" to="/coordinator/attendance">Manage attendance</Link><Link className="btn btn-outline-primary" to="/coordinator/tasks">Team tasks</Link><Link className="btn btn-outline-danger" to="/coordinator/incidents">Incident response</Link></div><p className="text-muted small mt-3 mb-0">Operational notifications continue through the notification bell and assigned-team task updates.</p></div></RoleLayout>}
function Info({label,value}){return <div className="col-md-4"><small className="text-muted">{label}</small><div className="fw-semibold">{value}</div></div>};function Panel({title,rows,render}){return <div className="col-lg-4"><div className="admin-bento-card h-100"><h2 className="h5 fw-bold">{title}</h2>{rows.length?rows.slice(0,6).map((x,i)=><div className="border-top py-2" key={x.id||i}>{render(x)}</div>):<p className="text-muted">No {title.toLowerCase()} added.</p>}</div></div>};function format(v){return v?new Date(v).toLocaleString():"Not added"}
