import { useEffect,useState } from "react";
import RoleLayout from "../../layouts/RoleLayout";
import api from "../../api/axiosConfig";
import { filterToActiveEvent, loadRoleAssignments } from "../../utils/roleAssignments";
import "../../styles/Admin.css";
export default function CoordinatorIncidents(){const [rows,setRows]=useState([]),[editing,setEditing]=useState(null),[error,setError]=useState("");
 async function load(){try{const id=localStorage.getItem("userId"),a=await loadRoleAssignments("COORDINATOR",`/coordinator-assignments/coordinator/${id}`);const results=await Promise.all(filterToActiveEvent(a).filter(x=>x.active!==false&&x.event?.id).map(async x=>({event:x.event,items:(await api.get(`/events/${x.event.id}/operations/incidents`)).data||[]})));setRows(results.flatMap(r=>r.items.map(i=>({...i,eventInfo:r.event}))));setError("");}catch(e){setError(e.response?.data?.message||"Unable to load incident reports.");}}
 useEffect(()=>{load();},[]); async function save(e){e.preventDefault();try{const payload={title:editing.title,description:editing.description,category:editing.category,severity:editing.severity,status:editing.status,location:editing.location,evidenceUrl:editing.evidenceUrl,assignedUserId:editing.assignedUserId,assignedUserName:editing.assignedUserName,resolutionNotes:editing.resolutionNotes};await api.put(`/events/${editing.eventInfo.id}/operations/incidents/${editing.id}`,payload);setEditing(null);load();}catch(e){setError(e.response?.data?.message||"Unable to update incident.");}}
 return <RoleLayout><div className="mb-4"><h1 className="fw-bold fs-3">Incidents</h1><p className="text-muted">Review reports from the assigned team, record a response, and track resolution.</p></div>{error&&<div className="alert alert-danger">{error}</div>}{editing&&<form className="admin-bento-card mb-4" onSubmit={save}><h2 className="h5 fw-bold">Respond to: {editing.title}</h2><div className="row g-3"><div className="col-md-4"><label className="form-label">Status</label><select className="form-select" value={editing.status||"OPEN"} onChange={e=>setEditing({...editing,status:e.target.value})}>{["OPEN","IN_PROGRESS","RESOLVED","CLOSED"].map(x=><option key={x}>{x}</option>)}</select></div><div className="col-md-8"><label className="form-label">Coordinator response / resolution</label><textarea required className="form-control" value={editing.resolutionNotes||""} onChange={e=>setEditing({...editing,resolutionNotes:e.target.value})}/></div></div><button className="btn btn-primary mt-3">Save response</button><button type="button" className="btn btn-light mt-3 ms-2" onClick={()=>setEditing(null)}>Cancel</button></form>}
 <div className="admin-bento-card"><div className="table-responsive"><table className="table align-middle"><thead><tr><th>Incident</th><th>Event</th><th>Reported by</th><th>Severity</th><th>Status</th><th>Response</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.title}</b><div className="text-muted small">{x.location||x.category}</div></td><td>{x.eventInfo?.eventName}</td><td>{x.reportedByName||"Team member"}</td><td>{x.severity}</td><td>{String(x.status).replaceAll("_"," ")}</td><td><button className="btn btn-sm btn-outline-primary" onClick={()=>setEditing(x)}>Review & respond</button></td></tr>)}{!rows.length&&<tr><td colSpan="6" className="text-center text-muted py-4">No incident reports for assigned events.</td></tr>}</tbody></table></div></div></RoleLayout>}
